### ISSUE TITLE
[f] authentication

### ISSUE THREAD

**Issue by tungbinhdinh89** [oclockvn/megax#9]
## Requirements
Make application more secure by requiring user to login before they can access other pages

## Todo

- [ ] Add a blank dashboard page, page url will be `/`
- [ ] Add a nav menu (simple one) with 2 links, `/` to dashboard and `/login` to the login page
- [ ] After login success, redirect to dashboard

**Comment by tungbinhdinh89** [comment]
Make application more secure by requiring user to login before they can access other pages:
Step 1: 
const [token, setToken] = useState();

  if (!token) {
    return <Login setToken={setToken} />;
  }
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/dashboard" element={<Dashboard />} />
        <Route path="/preference" element={<Preference />} />
      </Routes>
    </BrowserRouter>
  );

Step 2: 
Create file server.js in root folder:

const express = require("express");
const cors = require("cors");
const app = express();

app.use(cors());

app.use("/login", (req, res) => {
  res.send({
    token: "test123",
  });
});

app.listen(8080, () =>
  console.log("API is running on http://localhost:8080/login")
);

then run server : 
node server.js

step 3: in Login.js
_ get setToken prop from app.js

_ create function async with name loginUser and credentials as a argument:
async function loginUser(credentials) {
  return fetch("http://localhost:8080/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(credentials),
  }).then((data) => data.json());
}
